services:
  mysqldb:
    image: mysql:8.0
    container_name: mysqlContainer
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    volumes:
      - ./dbinit/init.sql:/docker-entrypoint-initdb.d/0_init.sql
      - D:/Docker/mysql_data:/var/lib/mysql
    ports:
      - 3308:3306
    expose:
      - 3306
    environment:
      MYSQL_DATABASE: patientsdb
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: admin
      SERVICE_TAGS: dev
      SERVICE_NAME: mysqldb
    networks:
      - internalnet

networks:
  internalnet:
    driver: bridge
